config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :posts
  resources :categories
  resources :comments

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :terms
	has_many :posts, :through => :terms

	def to_s
		title
	end
	
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	validates :content, presence: true, length: { minimum: 5 }
	belongs_to :post
	belongs_to :user

	def to_s
		"'#{content[0,15]}..' by user '#{user}'"
	end
	
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, presence: true
	validates :excerpt, presence: true
	validates :content, presence: true
	validates_presence_of :categories

	scope :current, -> { where("created_at >= '#{Time.now}'") }

	belongs_to :user
	has_many :terms
	
	has_many :categories, :through => :terms
	
	has_many :comments, dependent: :destroy

	def to_s
		title
	end
	
end

app/models/term.rb
class Term < ActiveRecord::Base

	belongs_to :post
	belongs_to :category
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def to_s
  	"#{fname} #{lname}"
  end
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fname
    devise_parameter_sanitizer.for(:sign_up) << :lname
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
  	@category = Category.find(params[:id])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!

	def create
		@comment = Comment.new(params[:comment].permit(:content, :post_id))
		@comment.user = current_user
		respond_to do |format|
			if @comment.save
				UserMailer.commentposted_email(@comment).deliver
				format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
				format.js   {}
				format.json { render json: @comment, status: :created, location: @comment }
			else
				format.html { render action: "new" }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate_user!, :only => [:new, :create]

	def index
		@posts = Post.current.order('created_at desc').paginate(:page => params[:page])
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		@comment.post = @post
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :excerpt, :content, :category_ids))
		@post.user = current_user

		if @post.save
			flash[:notice] = 'Post Created'
			redirect_to @post
		else
			flash[:alert] = @post.errors.full_messages.join(", ")
			render 'new'
		end	
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post].permit(:title, :excerpt, :content, :category_ids))
			flash[:notice] = "Post Updated"
			redirect_to @post
		else
			flash[:alert] = @post.errors.full_messages.join(", ")
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:notice] = 'Post Deleted'
		redirect_to :back
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def categories_unordered_list
		content_tag :ul do
			Category.order('title desc').collect { |c| concat(content_tag(:li, link_to(c, c))) }
		end
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def category_date_author_comments(post)
		raw("<div class=""post_details"">Posted in #{raw(post.categories.map { |c| link_to(c.title, c) }.join(', '))} on #{post.created_at.strftime('%m/%d/%Y')} by #{post.user} | #{link_to(pluralize(post.comments.size, 'Comment'), post_path(post, anchor: 'commentlabel'))}</div>")
	end

	def author_edit_link(post)
		if user_signed_in? && post.user == current_user
			return raw("<div class=""author_edit_post"">#{link_to 'Edit Post', edit_post_path(post), data: { 'no-turbolink'=>true}}</div>")
		end
		return ''
	end

	def author_delete_link(post)
		if user_signed_in? && post.user == current_user
			return raw("<div class=""author_delete_post"">#{link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }}</div>")
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/show.html.erb
<h1>Category <em><%= @category %></em></h1>

<section class="listing">
	<%= render partial: 'posts/post', collection: @category.posts.order('created_at desc') %>
</section>

app/views/comments/_comment.html.erb
<div class="comment">
	<h3>On <%= comment.created_at.strftime('%m/%d/%Y %I:%M %p') %> <%= comment.user %> said: </h3>
	<%= raw(comment.content) %>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for(@comment, remote:true) do |f| %>
	<%= f.hidden_field :post_id %>
	<%= f.text_area :content %>
	<br><%= submit_tag 'Comment' %>
<% end %>

app/views/comments/create.js.erb
$('<div class="comment"><%= escape_javascript(render @comment) %></div>').insertAfter('form#new_comment');
$('span#num_comments').html(<%= @comment.post.comments.size %>);
$('textarea#comment_content').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walaugelap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Walaugelap</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <%= categories_unordered_list %>
          </ul>
        </li>
                <% if user_signed_in? %>
                <li><%= link_to "New Post", new_post_path, data: { 'no-turbolink'=>true} %></li>
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in",   new_user_session_path %></li>
                <% end %>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    
    <div class="main-page-content <%= controller.controller_name %>">
    <%= yield %>
    </div>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :excerpt %>
		<%= f.text_field :excerpt %>
	</div>
	<div class="checkboxes">
		<label class="block">Categories</label>
		<%= f.collection_select(:category_ids, Category.all, :id, :title, prompt: true) %>
	</div>
	<div>
		<%= f.label :content %>
		<%= f.cktext_area :content %>
	</div>
	<div>
		<%= f.submit @post.new_record? ? "Create Post" : "Update Post"  %>
	</div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
	<h2><%= link_to post, post %></h2>
	<p><%= raw(post.excerpt) %></p>
	<%= category_date_author_comments(post) %>
	<%= author_edit_link(post) %>
	<%= author_delete_link(post) %>
	<p><%= link_to raw('Read More &raquo;'), post %></p>
</article>

app/views/posts/edit.html.erb
<h1>Edit <%= @post %></h1>
<article class="form">
	<%= render 'form' %>
</article>

app/views/posts/index.html.erb
<h1>Posts</h1>

<section class="listing">
	<%= render @posts %>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>
<article class="form">
	<%= render 'form' %>
</article>

app/views/posts/show.html.erb
<h1><%= @post %></h1>
<article class="fullpost">
	<%= category_date_author_comments(@post) %>
	<%= simple_format @post.content %>

	<section class="comments">
		<h2 id="commentlabel">Comments (<span id="num_comments"><%= @post.comments.size %></span>)</h2>
		<% if user_signed_in? %>
			<%= render 'comments/form' %>
		<% else %>
			<p><em>You must <%= link_to 'login', new_user_session_path %> to post comments</em></p>
		<% end %>
		<%= render partial: 'comments/comment', collection: @post.comments.order('created_at desc') %>
	</section>
</article>

app/views/welcome/index.html.erb
<center>
<% if user_signed_in? %>
<h2>Just <%= link_to "create post", new_post_path %> and share ... </h2>
<% else %>
<h2>Just <%= link_to "Sign in",   new_user_session_path %> and share ... </h2>
 <% end %>
<hr>
<%= link_to image_tag("move1.gif", alt: "move1"), new_post_path %>
<hr>
<h3><%= link_to " 'Every sinner has a future, every saint has a past' ", about_index_path %></h3>
</center>